// English defaults of Pulse. Apps pass their own dictionary through `labels` (merged one level deep, so
// `labels.fields` or `labels.summaries` can be given alone).
export const PULSE_LABELS = {
  listLabel: 'History',
  periods: {
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This week',
    thisMonth: 'This month',
    earlier: 'Earlier',
  },
  emptyTitle: 'Nothing has happened here yet',
  emptyHint: 'Every change to this record shows up here, with who made it and when.',
  loadFailed: 'Could not load the history',
  retry: 'Try again',
  showEarlier: 'Show earlier events',
  historyStart: 'This is where the history starts',
  backToList: 'All events',
  whatChanged: 'What changed',
  noFieldDetail: 'This event keeps no field detail, only its summary.',
  fromApp: (app) => `From ${app}`,
  before: 'Before',
  after: 'After',
  noValue: 'No value',
  changed: 'Changed',
  quoted: (text) => `“${text}”`,
  yes: 'Yes',
  no: 'No',
  someone: 'Someone',
  organization: 'Organization',
  unknownOrganization: 'Another organization',
  reason: 'Reason',
  verbTitles: {
    created: 'Created',
    updated: 'Updated',
    assigned: 'Assignee changed',
    state_changed: 'Status changed',
    subtask_added: 'Child record added',
    archived: 'Archived',
    unarchived: 'Restored',
    restored: 'Restored',
    deleted: 'Deleted',
    dispatched: 'Dispatched',
    transferred: 'Transferred to another organization',
    referred: 'Referred to another organization',
    derived_completed: 'Derived work completed',
    taken: 'Taken from the queue',
    review_requested: 'Review requested',
    approved: 'Approved',
    rejected: 'Rejected',
    fallback: 'Activity',
  },
  summaries: {
    created: 'Created this record',
    receivedFrom: (organization) => `Arrived from ${organization}`,
    moved: (from, to) =>
      from ? `Changed the status from ${from} to ${to}` : `Set the status to ${to}`,
    assigned: (who) => `Assigned it to ${who}`,
    assignedSomeone: 'Changed the assignee',
    unassigned: 'Removed the assignee',
    updated: (fields) => `Changed the ${fields}`,
    updatedSomething: 'Updated this record',
    subtaskAdded: (title) => `Added the child record “${title}”`,
    subtaskAddedSomething: 'Added a child record',
    archived: 'Archived this record',
    unarchived: 'Restored this record',
    restored: 'Restored this record',
    deleted: 'Deleted this record',
    dispatched: (place) => `Dispatched it to ${place}`,
    dispatchedSomewhere: 'Dispatched it to another place',
    transferred: (organization) => `Transferred it to ${organization}`,
    referred: (organization) => `Referred work to ${organization}`,
    derivedCompleted: (organization) => `${organization} completed the derived work`,
    taken: 'Took it from the queue',
    reviewRequested: 'Asked for a review',
    approved: 'Approved it',
    rejected: 'Rejected it',
  },
  fields: {},
};

export const mergePulseLabels = (labels = {}) => ({
  ...PULSE_LABELS,
  ...labels,
  periods: { ...PULSE_LABELS.periods, ...labels.periods },
  verbTitles: { ...PULSE_LABELS.verbTitles, ...labels.verbTitles },
  summaries: { ...PULSE_LABELS.summaries, ...labels.summaries },
  fields: { ...PULSE_LABELS.fields, ...labels.fields },
});
